name: mucke
description: music player
publish_to: none

version: 1.5.1+12

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  async_task: ^1.1.1
  audio_service: ^0.18.18  # MIT
  audio_session: ^0.2.2  # MIT
  collection: ^1.19.1  # BSD 3
  device_info_plus: ^12.1.0  # BSD 3
  drift: ^2.28.1  # MIT
  equatable: ^2.0.7  # MIT
  file_picker: ^10.3.3  # MIT
  fimber: ^0.7.0  # Apache 2.0
  fimber_io: ^0.7.0  # Apache 2.0
  flutter:
    sdk: flutter
  flutter_fimber: ^0.7.1  # Apache 2.0
  #flutter_gen: ^5.11.0
  flutter_localizations:
    sdk: flutter
  flutter_mobx: ^2.3.0  # MIT
  flutter_speed_dial: ^7.0.0  # MIT
  get_it: ^8.2.0  # MIT
  image: ^4.5.4
  intl: ^0.20.2
  just_audio: ^0.10.5  # MIT
  metadata_god:
    git:
      url: https://github.com/FriederHannenheim/metadata_god.git
      rev: HEAD
      path: packages/metadata_god
  mobx: ^2.5.0  # MIT
  optimization_battery: ^0.0.7  # MIT
  package_info_plus: ^9.0.0
  page_indicator_plus: ^1.0.4  # MIT
  path: ^1.9.1  # BSD 3
  path_provider: ^2.1.5  # BSD 3
  permission_handler: ^12.0.1  # MIT
  provider: ^6.1.5+1  # MIT
  reorderables: ^0.6.0  # MIT
  share_plus: ^12.0.0
  sqlite3_flutter_libs: ^0.5.39  # MIT
  string_similarity: ^2.1.1  # MIT
  text_scroll: ^0.2.1  # MIT

dev_dependencies:
  build_runner: ^2.7.1  # BSD 3
  drift_dev: ^2.28.2  # MIT
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.7.2  # MIT
  mockito: ^5.5.0
  test: ^1.26.2


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  generate: true  # added for l10n

  uses-material-design: true
  assets:
    - assets/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family:  MuckeIcons
      fonts:
        - asset: fonts/MuckeIcons.ttf

  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
